package frc.robot;

import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.Slot0Configs;

// import com.ctre.phoenix.motorcontrol.SupplyCurrentLimitConfiguration;
// import com.ctre.phoenix.motorcontrol.can.TalonFXConfiguration;
// import com.ctre.phoenix.sensors.AbsoluteSensorRange;
// import com.ctre.phoenix.sensors.CANCoderConfiguration;
// import com.ctre.phoenix.sensors.SensorInitializationStrategy;
// import com.ctre.phoenix.sensors.SensorTimeBase;
import static frc.robot.Constants.ElevatorK.*;

public final class CTREConfigs {
    private static final class Container {
        public static final CTREConfigs INSTANCE = new CTREConfigs();
    }

    public static CTREConfigs Get() {
        return Container.INSTANCE;
    }

    public final TalonFXConfiguration swerveAngleFXConfig = new TalonFXConfiguration();
    public final TalonFXConfiguration swerveDriveFXConfig = new TalonFXConfiguration();
    public final CANcoderConfiguration swerveCanCoderConfig = new CANcoderConfiguration();
    public final TalonFXConfiguration rightConfig = new TalonFXConfiguration();
    public final TalonFXConfiguration leftConfig = new TalonFXConfiguration();

    private CTREConfigs() {
        /* commented out bc hopefullyyyyy autogenerated code will save my life (plsplspls) */
        // /* Swerve Angle Motor Configurations */
        // CurrentLimitsConfigs angleSupplyLimit = new CurrentLimitsConfigs();
        // // new SupplyCurrentLimitConfiguration(
        // //         Constants.SwerveK.kAngleEnableCurrentLimit,
        // //         Constants.SwerveK.kAngleContinuousCurrentLimit,
        // //         Constants.SwerveK.kAnglePeakCurrentLimit,
        // //         Constants.SwerveK.kAnglePeakCurrentDuration);

        // var SwerveAngleFXSlot0Configs = swerveAngleFXConfig.Slot0;
        // SwerveAngleFXSlot0Configs.kP = Constants.SwerveK.kAngleKP;
        // SwerveAngleFXSlot0Configs.kI = Constants.SwerveK.kAngleKI;
        // SwerveAngleFXSlot0Configs.kD = Constants.SwerveK.kAngleKD;
        // SwerveAngleFXSlot0Configs.kV = Constants.SwerveK.kAngleKF;

        // /* Swerve Drive Motor Configuration */
        // CurrentLimitsConfigs driveSupplyLimit = new CurrentLimitsConfigs();
        // // SupplyCurrentLimitConfiguration driveSupplyLimit = new SupplyCurrentLimitConfiguration(
        // //         Constants.SwerveK.kDriveEnableCurrentLimit,
        // //         Constants.SwerveK.kDriveContinuousCurrentLimit,
        // //         Constants.SwerveK.kDrivePeakCurrentLimit,
        // //         Constants.SwerveK.kDrivePeakCurrentDuration);

        // var SwerveDriveFXSlot0Configs = swerveDriveFXConfig.Slot0;
        // SwerveDriveFXSlot0Configs.kP = Constants.SwerveK.kDriveKP;
        // SwerveDriveFXSlot0Configs.kI = Constants.SwerveK.kAngleKI;
        // SwerveDriveFXSlot0Configs.kD = Constants.SwerveK.kAngleKD;
        // SwerveDriveFXSlot0Configs.kV = Constants.SwerveK.kAngleKF;
        // swerveDriveFXConfig.

        // swerveDriveFXConfig.supplyCurrLimit = driveSupplyLimit;
        // swerveDriveFXConfig.openloopRamp = Constants.SwerveK.kOpenLoopRamp;
        // swerveDriveFXConfig.closedloopRamp = Constants.SwerveK.kClosedLoopRamp;

        // /* Swerve CANCoder Configuration */
        // swerveCanCoderConfig.absoluteSensorRange = AbsoluteSensorRange.Unsigned_0_to_360;
        // swerveCanCoderConfig.sensorDirection = Constants.SwerveK.kInvertCanCoder;
        // swerveCanCoderConfig.initializationStrategy = SensorInitializationStrategy.BootToAbsolutePosition;
        // swerveCanCoderConfig.sensorTimeBase = SensorTimeBase.PerSecond;

        /* Elevator Left and Right Motor Configuration */
        CurrentLimitsConfigs eleSupplyLimit = new CurrentLimitsConfigs();
        /* not sure if this is correct? but i'm guessing lol */
        // SupplyCurrentLimitConfiguration elevatorSupplyLimit = new SupplyCurrentLimitConfiguration(
        //         kEnableCurrentLimit,
        //         kContinuousCurrentLimit,
        //         kPeakCurrentLimit,
        //         kPeakCurrentDuration);

        var rightSlot0Configs = rightConfig.Slot0;
        rightSlot0Configs.kP = kP;
        rightSlot0Configs.kD = kD;

        rightConfig.reverseSoftLimitThreshold = kReverseLimit;
        rightConfig.forwardSoftLimitThreshold = kForwardLimit;
        rightConfig.forwardSoftLimitEnable = kEnableForwardLimit;
        rightConfig.reverseSoftLimitEnable = kEnableReverseLimit;

        rightConfig.supplyCurrLimit = elevatorSupplyLimit;
        leftConfig.supplyCurrLimit = elevatorSupplyLimit;
    }
}